name: Update README

on:
  push:
  # schedule:
  #  - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@master
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@master
      - name: Install dependencies
        run: install.packages('rmarkdown')
        shell: Rscript {0}
      - name: Knit README.Rmd
        run: rmarkdown::render('README.Rmd')
        shell: Rscript {0}
      - name: Add GitHub Activity
        uses: jamesgeorge007/github-activity-readme@v0.1.7
        env:
          GITHUB_TOKEN: ${secrets.GITHUB_TOKEN}
