name: Update README

on:
  push:
  # schedule:
  #  - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container: rocker/r-base
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Pandoc
        run: apt update && apt install -y pandoc
      - name: Install dependencies
        run: install.packages('rmarkdown')
        shell: Rscript {0}
      - name: Knit README.Rmd
        run: rmarkdown::render('README.Rmd')
        shell: Rscript {0}
